motd: hi

# Site settings
title: HTML55 GAMES
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Big collection of free games with no ads
baseurl: "/html55" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
issue_url: https://github.com/mochawoof/html55/issues/new

new55: 259200 # 60s * 60 * 24 * 3
timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty

#include some js
include: ["__*.js"]

#collections
collections:
  games:
    output: true
