motd: high quality games with no ads

# Site settings
title: HTML55 GAMES
# email: your-email@domain.com
description: >
  Big collection of only the BEST free games with no ads
baseurl: ""
# url: "http://yourdomain.com" # unused
github_url: https://github.com/mochawoof/mochawoof.github.io/issues/new # don't use a trailing slash here

new55: 172800 # how new a post should be to get the NEW badge * 60 * 24 * 2
timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty

# fix embeds
include: ["_*.*"]

# collections
collections:
  games:
    output: true
  other:
    output: true