motd: free games, no ads

# Site settings
title: HTML55 GAMES
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Big collection of free games with no ads
baseurl: "/" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
issue_url: https://github.com/mochawoof/mochawoof.github.io/issues/new

new55: 172800 # 60s * 60 * 24 * 2
timezone: America/New_York

# Build settings
markdown: kramdown
permalink: pretty

#fix embeds
include: ["_*.*"]

#collections
collections:
  games:
    output: true
