# Site settings
title: HTML55 GAMES
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Big collection of free games with no ads
baseurl: "/html55" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mochawoof

# Build settings
markdown: kramdown
permalink: pretty
